language: php

php:
  - 7.0
  - 7.1
  - nightly
  - hhvm

before_script:
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - php -S localhost:8000 -t public/ &
  - sleep 3 # give xvfb some time to start
  - composer install

script:
  - composer test

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly
    - php: hhvm
