language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
  - java -jar selenium-server-standalone-2.53.1.jar > /dev/null &
  - php -S localhost:8000 -t public/ > /dev/null &
  - sleep 3 # give xvfb some time to start
  - composer install

script:
  - composer test

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly
